---
resources:
    - name: git-repo
      type: git
      source:
          uri: https://github.com/varesa/s3-rpmrepo-automation
          branch: master

    - name: container-image
      type: docker-image
      source:
          repository: registry.esav.fi/tools/s3-rpmrepo
          username: ((autom_username))
          password: ((autom_password))

jobs:
    - name: Build and publish container
      public: true
      serial: true
      plan:
          - get: git-repo
          - put: container-image
            params:
                build: git-repo

    - name: Update RPM repo
      public: true
      plan:
          # Do this to get the dependency in the graph
          - get: container-image
            passed: ["Build and publish container"]

          - task: update
            config:
                platform: linux

                image_resource:
                    type: docker-image
                    source: { repository: registry.esav.fi/tools/s3-rpmrepo }

                run:
                    path: bash
                    args:
                        - -euc
                        - |
                            set +x
                            echo ""
                            echo "########################"
                            echo "# Downloading new RPMs #"
                            echo "########################"
                            echo ""
                            set -x

                            mkdir /tmp/new_rpms
                            aws s3 sync s3://rpmrepo-1-ingest-b54e8/ /tmp/new_rpms/

                            set +x
                            echo ""
                            echo "###########################"
                            echo "# Updating the repository #"
                            echo "###########################"
                            echo ""
                            set -x

                            cd /tmp/new_rpms/
                            for rpm in *.rpm; do
                                distro=$(rpm -q --qf "%{RELEASE}\n" $rpm | grep -E -o 'fc[0-9]{2}|el[0-9]')
                                [ -n "$distro" ] || (echo "Unable to figure out distro for $rpm"; exit 1)
                                /rpm-s3/bin/rpm-s3 -b rpmrepo-1-43ybe46n6 -p "$distro/" -r eu-west-1 $rpm
                                aws s3 rm s3://$INPUT_BUCKET/$rpm
                            done
                params:
                    AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
                    AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
                    INPUT_BUCKET: rpmrepo-1-ingest-b54e8
                    OUTPUT_BUCKET: rpmrepo-1-43ybe46n6

